In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [3]:
##load the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [ ]:
###Preprocess the Data 
##Drop irrelevant columns
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [5]:
## Encode Categorical variables
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [11]:
## one hot encoding
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[['Geography']])

In [16]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [18]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

In [19]:
#combine one hot encoder columns with original data
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [ ]:
##Save the encoders and scaler
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

In [21]:
with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [22]:
#divide the feature into dependent and independent features
X=data.drop('Exited',axis=1)
Y=data['Exited']

In [24]:
#Split the data into  training and testing sets
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [25]:
#Scale the features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [57]:
#Save the StandardScaler as pickle file
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

ANN Implementation

In [28]:
import tensorflow as tf

WARNING:tensorflow:From c:\Users\AdithyaP\OneDrive\Documents\annclassification1\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [31]:
#Build our ANN Model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),#HL1 connected to input layer
    Dense(32,activation='relu',),#HL2
    Dense(1,activation='sigmoid'),## output Layer
])

WARNING:tensorflow:From c:\Users\AdithyaP\OneDrive\Documents\annclassification1\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [32]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [39]:
opt=tf.keras.optimizers.Adam(learning_rate=0.01)
loss=tf.keras.losses.BinaryCrossentropy()
loss

In [42]:
##Compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=['accuracy'])

In [45]:
#Set up the Tensorboard
log_dir="logs/fit"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tf_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [49]:
#Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [50]:
##Train the model
history=model.fit(
    X_train,Y_train,validation_data=(X_test,Y_test),epochs=100,
    callbacks=[tf_callback,early_stopping_callback]

)

Epoch 1/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3511 - accuracy: 0.8574 - val_loss: 0.3438 - val_accuracy: 0.8615
Epoch 2/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3451 - accuracy: 0.8594 - val_loss: 0.3527 - val_accuracy: 0.8595
Epoch 3/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3397 - accuracy: 0.8608 - val_loss: 0.3395 - val_accuracy: 0.8600
Epoch 4/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3392 - accuracy: 0.8620 - val_loss: 0.3415 - val_accuracy: 0.8615
Epoch 5/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3385 - accuracy: 0.8614 - val_loss: 0.3422 - val_accuracy: 0.8620
Epoch 6/100
250/250 [==============================] - 2s 8ms/step - loss: 0.3347 - accuracy: 0.8633 - val_loss: 0.3492 - val_accuracy: 0.8585
Epoch 7/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3341 - accuracy: 0.8651 - val_loss: 0.3661 - val_accuracy: 0.8525
Epoch 8/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3300 - accuracy: 0.8631 - val_loss: 0.3653 - val_accuracy: 0.8615
Epoch 9/100
250/250 [==============================] - 2s 9ms/step - loss: 0.3307 - accuracy: 0.8652 - val_loss: 0.3635 - val_accuracy: 0.8550
Epoch 10/100
250/250 [==============================] - 3s 10ms/step - loss: 0.3284 - accuracy: 0.8665 - val_loss: 0.3395 - val_accuracy: 0.8620
Epoch 11/100
250/250 [==============================] - 3s 10ms/step - loss: 0.3277 - accuracy: 0.8621 - val_loss: 0.3409 - val_accuracy: 0.8605
Epoch 12/100
250/250 [==============================] - 4s 14ms/step - loss: 0.3261 - accuracy: 0.8665 - val_loss: 0.3460 - val_accuracy: 0.8530
Epoch 13/100
250/250 [==============================] - 3s 12ms/step - loss: 0.3234 - accuracy: 0.8679 - val_loss: 0.3654 - val_accuracy: 0.8515
Epoch 14/100
250/250 [==============================] - 3s 11ms/step - loss: 0.3206 - accuracy: 0.8675 - val_loss: 0.3554 - val_accuracy: 0.8560
Epoch 15/100
250/250 [==============================] - 3s 12ms/step - loss: 0.3177 - accuracy: 0.8698 - val_loss: 0.3613 - val_accuracy: 0.8560
Epoch 16/100
250/250 [==============================] - 3s 11ms/step - loss: 0.3202 - accuracy: 0.8670 - val_loss: 0.3557 - val_accuracy: 0.8595
Epoch 17/100
250/250 [==============================] - 3s 11ms/step - loss: 0.3186 - accuracy: 0.8691 - val_loss: 0.3426 - val_accuracy: 0.8630
Epoch 18/100
250/250 [==============================] - 3s 12ms/step - loss: 0.3149 - accuracy: 0.8679 - val_loss: 0.3562 - val_accuracy: 0.8605
Epoch 19/100
250/250 [==============================] - 3s 11ms/step - loss: 0.3117 - accuracy: 0.8714 - val_loss: 0.3597 - val_accuracy: 0.8555
Epoch 20/100
250/250 [==============================] - 3s 12ms/step - loss: 0.3124 - accuracy: 0.8705 - val_loss: 0.3648 - val_accuracy: 0.8600

In [51]:
model.save('model.h5')

c:\Users\AdithyaP\OneDrive\Documents\annclassification1\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [52]:
#Load TensorBoard extension
%load_ext tensorboard

In [56]:
%tensorboard --logdir logs/fit20260304-103638

Reusing TensorBoard on port 6008 (pid 37248), started 0:00:08 ago. (Use '!kill 37248' to kill it.)