In [2]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [76]:
###Load the trained model ,Scaler pickle file,one hot encoder
model=load_model('model.h5')

##load the encoder and scaler
with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_gender=pickle.load(file)
with open('onehot_encoder_geo.pkl','rb') as file:
    onehot_encoder_geo=pickle.load(file)
with open('scaler.pkl','rb') as file:
    scaler_1=pickle.load(file)

In [ ]:
input_data = {
    "CreditScore": 619,
    "Geography":"France",
    "Gender":"Female",
    "Age": 42,
    "Tenure": 2,
    "Balance": 0.0,
    "NumOfProducts": 1,
    "HasCrCard": 1,
    "IsActiveMember": 1,
    "EstimatedSalary": 101348.9
}

In [14]:
geo_encoder=onehot_encoder_geo.transform([[input_data['Geography']]])

c:\Users\AdithyaP\OneDrive\Documents\annclassification1\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [18]:
geoencoder_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geoencoder_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [54]:
input_df=pd.DataFrame([input_data])

In [55]:
input_df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.0,1,1,1,101348.9

In [56]:
input_df['Gender']=label_encoder_gender.transform(input_df['Gender'])

In [57]:
input_df=pd.concat([input_df.drop("Geography",axis=1),geoencoder_df],axis=1)

In [58]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.0,1,1,1,101348.9,1.0,0.0,0.0

In [75]:
print(type(scaler_1))

<class 'str'>

In [77]:
input_scaled=scaler_1.transform(input_df)

In [78]:
input_scaled

array([[-0.27700291, -1.09997489,  0.28778948, -1.03940009, -1.25599716,
        -0.89163935,  0.63367318,  0.95214374,  0.04564946,  0.98019606,
        -0.57581067, -0.56349184]])

In [80]:
prediction=model.predict(input_scaled)

1/1 [==============================] - 0s 35ms/step

In [81]:
print(prediction[0][0])

0.20620903

In [ ]:
if(prediction[0][0]>0.5):
    print("The customer is likely to get churn")
else:
    print("The customer is not likely to churn")

The customer is not likely to churn